server:
  port: 8080 # 충돌 문제 시 수정
spring:
  # Security
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
# JWT
jwt:
  # openssl rand -base64 32
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS} # 1시간
# Swagger
# 여러 가지 설정 on-off 및 dev, prod 분기
springdoc:
  swagger-ui:
    # enabled: true # 개발 환경에선
    enabled: false # 배포 환경에선
  api-docs:
    # enabled: true # 개발 환경에선
    enabled: false # 배포 환경에선